name: Update capas

on:
  schedule:
    - cron: '0 7 * * *'
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: capas-api  # ðŸ‘ˆ muda o diretÃ³rio base

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Instalar Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Compilar em modo release
        run: cargo build --release

      - name: Executar scraper
        run: ./target/release/capas-api

      - name: Deploy para gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./capas-api/public   # ðŸ‘ˆ ajustado para apontar Ã  pasta certa
          publish_branch: gh-pages
          commit_message: "ðŸ”„ Update capas ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}'

      - name: Send Push Notification
        if: github.event_name == 'workflow_dispatch' || github.event.schedule == '0 8 * * *'
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          PROJECT_ID=$(jq -r .project_id <<< '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}')
          
          curl -X POST -H "Authorization: Bearer $ACCESS_TOKEN" \
          -H "Content-Type: application/json" \
          -d '{
            "message": {
              "topic": "updates",
              "notification": {
                "title": "Jornais Atualizados",
                "body": "As capas de hoje jÃ¡ estÃ£o disponÃ­veis!"
              }
            }
          }' \
          "https://fcm.googleapis.com/v1/projects/$PROJECT_ID/messages:send"
